begin;

create table if not exists public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null,
  status text not null default 'draft'
    check (status in ('draft', 'in_review', 'approved', 'scheduled', 'published', 'archived')),
  readiness text not null default 'needs_revision'
    check (readiness in ('needs_revision', 'awaiting_evidence_review', 'ready')),
  publication_state text not null default 'draft_only'
    check (publication_state in ('draft_only', 'implemented_locally', 'live_confirmed', 'publication_unverified')),
  category text not null default '',
  excerpt text not null default '',
  content_blocks jsonb not null default '[]'::jsonb check (jsonb_typeof(content_blocks) = 'array'),
  cover_image_url text not null default '',
  cover_image_alt text not null default '',
  cover_image_caption text not null default '',
  cover_image_credit text not null default '',
  seo_title text not null default '',
  meta_description text not null default '',
  canonical_path text not null default '',
  og_title text not null default '',
  og_description text not null default '',
  og_image_url text not null default '',
  robots text not null default 'noindex, follow'
    check (robots in ('index, follow', 'noindex, follow', 'noindex, nofollow')),
  schema_type text not null default 'BlogPosting' check (schema_type in ('BlogPosting', 'Article')),
  breadcrumb_schema_enabled boolean not null default true,
  faq_schema_enabled boolean not null default true,
  faqs jsonb not null default '[]'::jsonb check (jsonb_typeof(faqs) = 'array'),
  related_slugs jsonb not null default '[]'::jsonb check (jsonb_typeof(related_slugs) = 'array'),
  annotations jsonb not null default '[]'::jsonb check (jsonb_typeof(annotations) = 'array'),
  editorial_brief jsonb not null default '{}'::jsonb check (jsonb_typeof(editorial_brief) = 'object'),
  author_name text not null default 'Shanaya''s Driving School',
  reviewer_name text not null default '',
  review_scope text not null default '',
  review_required boolean not null default false,
  reviewed_at timestamptz,
  scheduled_for timestamptz,
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_blog_posts_status_updated on public.blog_posts (status, updated_at desc);
create index if not exists idx_blog_posts_scheduled on public.blog_posts (scheduled_for)
  where status = 'scheduled';

create table if not exists public.blog_post_revisions (
  id uuid primary key default gen_random_uuid(),
  -- Intentionally not a foreign key: deleting a draft must not also erase its audit snapshots.
  blog_post_id uuid not null,
  revision_number bigint generated by default as identity,
  snapshot jsonb not null,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_blog_post_revisions_post_created
  on public.blog_post_revisions (blog_post_id, created_at desc);

drop trigger if exists trg_blog_posts_updated_at on public.blog_posts;
create trigger trg_blog_posts_updated_at
before update on public.blog_posts
for each row execute function public.set_updated_at();

create or replace function public.capture_blog_post_revision()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.blog_post_revisions (blog_post_id, snapshot, changed_by)
  values (old.id, to_jsonb(old), auth.uid());
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_capture_blog_post_revision on public.blog_posts;
create trigger trg_capture_blog_post_revision
before update or delete on public.blog_posts
for each row execute function public.capture_blog_post_revision();

alter table public.blog_posts enable row level security;
alter table public.blog_post_revisions enable row level security;

drop policy if exists "Admin users can read blog posts" on public.blog_posts;
create policy "Admin users can read blog posts"
on public.blog_posts for select to authenticated
using (public.is_admin_user());

drop policy if exists "Admin users can create blog posts" on public.blog_posts;
create policy "Admin users can create blog posts"
on public.blog_posts for insert to authenticated
with check (public.is_admin_user());

drop policy if exists "Admin users can update blog posts" on public.blog_posts;
create policy "Admin users can update blog posts"
on public.blog_posts for update to authenticated
using (public.is_admin_user()) with check (public.is_admin_user());

drop policy if exists "Admin users can delete blog posts" on public.blog_posts;
create policy "Admin users can delete blog posts"
on public.blog_posts for delete to authenticated
using (public.is_admin_user());

drop policy if exists "Admin users can read blog revisions" on public.blog_post_revisions;
create policy "Admin users can read blog revisions"
on public.blog_post_revisions for select to authenticated
using (public.is_admin_user());

revoke all on table public.blog_posts from anon, authenticated;
revoke all on table public.blog_post_revisions from anon, authenticated;
grant select, insert, update, delete on table public.blog_posts to authenticated;
grant select on table public.blog_post_revisions to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'blog-media',
  'blog-media',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view blog media" on storage.objects;
create policy "Public can view blog media"
on storage.objects for select to anon, authenticated
using (bucket_id = 'blog-media');

drop policy if exists "Admin users can upload blog media" on storage.objects;
create policy "Admin users can upload blog media"
on storage.objects for insert to authenticated
with check (bucket_id = 'blog-media' and public.is_admin_user());

drop policy if exists "Admin users can update blog media" on storage.objects;
create policy "Admin users can update blog media"
on storage.objects for update to authenticated
using (bucket_id = 'blog-media' and public.is_admin_user())
with check (bucket_id = 'blog-media' and public.is_admin_user());

drop policy if exists "Admin users can delete blog media" on storage.objects;
create policy "Admin users can delete blog media"
on storage.objects for delete to authenticated
using (bucket_id = 'blog-media' and public.is_admin_user());

commit;
